markdown        : kramdown
name            : Coderaiser
title           : Coderaiser
tagLine         : Coderaiser projects
viewOn          : View Project on
download        : Download
contact         : Contact
maintainedBy    : This project is maintained by
yandex          : 48e59eacd66f1bbd
metrika         : 24321379
ga              : UA-33536569-5
canonical       : coderaiser.github.io
repoName        : coderaiser/coderaiser.github.io/edit/master/index.md
improveText     : "Find typo? Help fix it."
repoSource      : coderaiser/coderaiser.github.io
